spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/eds?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: postgres
    password: kittu
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 8002
  servlet:
    context-path: /auth

  ssl:
    key-store: D:\TOKEN\keystore.p12
    key-store-password: 12345678
    key-alias: edsapp
    key-store-type: PKCS12

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 600000

springdoc:
  swagger-ui:
    path: /swagger.html

eds:
  app:
    entitlement: https://localhost:8003/entitlement